version: "3.7"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - 8001:8001
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: kartoza/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nimda
      - POSTGRES_PASS=yourpasswordhere
      - POSTGRES_DBNAME=admg_dev

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure

  celery_worker:
    command: celery -A config worker -l info
    container_name: celery_worker
    hostname: celery_worker
    build:
      context: .
    volumes:
      - .:/code
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - web
      - rabbitmq

  flower:
    image: mher/flower:0.9.5
    command: ["flower", "--broker=pyamqp://rabbitmq:5672", "--port=8888"]
    ports:
      - 8888:8888

volumes:
  postgres_data:
  static_volume:
  media_volume:
