version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: dev_nginx
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./mime.types:/etc/nginx/mime.types
       - ./staticfiles:/code/staticfiles
    ports:
       - 80:80
       - 443:443
    depends_on:
       - web
  db:
    image: kartoza/postgis
    environment:
       POSTGRES_PASS: postgres
       POSTGRES_USER: postgres
       POSTGRES_DBNAME: postgres
    volumes:
       - ./postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    environment:
            DJANGO_SECRET_KEY: somesecretkeygoeshereidontevencare
            DJANGO_SETTINGS_MODULE: config.settings.local
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    env_file:
      - env.dev
    expose:
      - 8000
    depends_on:
      - db