version: "3.7"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8001
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 5678:5678 # debugger
      - 8001:8001 # mapped to 8001 to prevent clashes with local django instances
      - 8890:8888 # allows use of django shell notebooks during local development
    env_file:
      - ./.env
    environment:
      - DB_NAME=admg_webapp
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - MIGRATE=true
    depends_on:
      - db

  db:
    image: postgis/postgis:12-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=admg_webapp
    ports:
      - "5439:5432"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5673:5672"
    restart: on-failure

  celery_worker:
    build:
      context: ./
      dockerfile: Dockerfile.local
    command: celery -A config worker -l info
    working_dir: /app
    container_name: celery_worker
    hostname: celery_worker
    volumes:
      - ./app:/app
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - DB_NAME=admg_webapp
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - MIGRATE=false
    depends_on:
      - web
      - rabbitmq

volumes:
  postgres_data:
  static_volume:
  media_volume:
