version: '3.7'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: kartoza/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nimda
      - POSTGRES_PASS=yourpasswordhere
      - POSTGRES_DBNAME=admg_dev

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure

  celery_worker:
    command: celery -A config worker -l info
    container_name: celery_worker
    hostname: celery_worker
    build:
      context: .
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - web
      - rabbitmq

volumes:
  postgres_data:
  static_volume:
  media_volume:
