version: "3.7"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - 5678:5678
      - 8001:8001 # mapped to 8001 to prevent clashes with local django instances
      - 8890:8888 # allows use of django shell notebooks during local development
    env_file:
      - ./.env
    environment:
      - MIGRATE=true
    depends_on:
      - db

  sass:
    build:
      context: ./
      dockerfile: Dockerfile.local
    command: python manage.py sass admin_ui/static/scss admin_ui/static/css --watch
    volumes:
      - .:/code
    env_file:
      - ./.env

  db:
    image: postgis/postgis:13-master
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=admg_webapp
    ports:
      - "5439:5432"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5673:5672"
    restart: on-failure

  celery_worker:
    command: celery -A config worker -l info
    container_name: celery_worker
    hostname: celery_worker
    build:
      context: ./
      dockerfile: Dockerfile.local
    volumes:
      - .:/code
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - MIGRATE=false
    depends_on:
      - web
      - rabbitmq

volumes:
  postgres_data:
  static_volume:
  media_volume:
