version: '3'
services:
  db:
    image: kartoza/postgis
    environment:
       POSTGRES_PASS: postgres
       POSTGRES_USER: postgres
       POSTGRES_DBNAME: admg_webapp
    volumes:
       - ./postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
