# pull official base image
FROM --platform=linux/amd64 python:3.11.1 AS builder

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set working directory
WORKDIR /app/home/app/web

# install dependencies
RUN apt-get update --fix-missing && apt-get install -y gdal-bin libgdal-dev postgis netcat

# install requirements
COPY requirements/ .
RUN pip install --upgrade pip
RUN pip install -r production.txt

COPY . .

ENTRYPOINT ["/app/home/app/web/entrypoint.sh"]
