version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: dev_nginx
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./mime.types:/etc/nginx/mime.types
       - ./staticfiles:/code/staticfiles
    ports:
       - 80:80
       - 443:443
    depends_on:
       - web
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    expose:
      - 8000
