# pull official base image
FROM python:3.11.1 AS builder

ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY requirements/ .
# RUN pip install -r local.txt
RUN pip install -r updated_requirements_baseandlocal.txt
RUN apt-get update --fix-missing && apt-get install -y gdal-bin libgdal-dev postgis netcat

COPY . /code/


# run entrypoint.sh
# ENTRYPOINT [ "/code/entrypoint.sh" ]
