from django.test import TestCase
from django.urls import reverse, NoReverseMatch


class TestChangeUpdateView(TestCase):

    def test_autogenerated_urls(self):
        """
        Autogenerated URLs for ChangeUpdateView exist in defined URL patterns.
        """
        from admin_ui.views import ChangeUpdateView

        failures = []
        for _, reverse_key in ChangeUpdateView.back_button_mapping.items():
            try:
                reverse(reverse_key)
            except NoReverseMatch:
                failures.append(reverse_key)

        if failures:
            self.fail(f"No reverse URL found for {', '.join(failures)}")
