from data_models.models import (
    PlatformType,
    MeasurementType,
    MeasurementStyle,
    HomeBase,
    FocusArea,
    Season,
    Repository,
    MeasurementRegion,
    GeographicalRegion,
    GeophysicalConcept,
    PartnerOrg,
    Alias,
    GcmdProject,
    GcmdInstrument,
    GcmdPlatform,
    GcmdPhenomena,
    DOI,
    Campaign,
    Platform,
    Instrument,
    Deployment,
    IOP,
    SignificantEvent,
    CollectionPeriod,
    Website,
    WebsiteType,
    CampaignWebsite,
)

from .published_tables import (
    PublishedPlatformTypeTable,
    PublishedMeasurementTypeTable,
    PublishedMeasurementStyleTable,
    PublishedHomeBaseTable,
    PublishedFocusAreaTable,
    PublishedSeasonTable,
    PublishedRepositoryTable,
    PublishedMeasurementRegionTable,
    PublishedGeographicalRegionTable,
    PublishedGeophysicalConceptTable,
    PublishedPartnerOrgTable,
    PublishedAliasTable,
    PublishedGcmdProjectTable,
    PublishedGcmdInstrumentTable,
    PublishedGcmdPlatformTable,
    PublishedGcmdPhenomenaTable,
    PublishedDOITable,
    PublishedCampaignTable,
    PublishedPlatformTable,
    PublishedInstrumentTable,
    PublishedDeploymentTable,
    PublishedIOPTable,
    PublishedSignificantEventTable,
    PublishedCollectionPeriodTable,
    PublishedWebsiteTable,
    PublishedWebsiteTypeTable,
    PublishedCampaignWebsiteTable,
)
from .published_filters import GenericPublishedListFilter

from api_app.urls import camel_to_snake

MODEL_CONFIG_MAP = {
    "PlatformType": {
        "display_name": camel_to_snake("PlatformType"),
        "url": "platform_types",
        "model": PlatformType,
        "table": PublishedPlatformTypeTable,
        "filter": GenericPublishedListFilter,
    },
    "MeasurementType": {
        "display_name": camel_to_snake("MeasurementType"),
        "url": "measurement_types",
        "model": MeasurementType,
        "table": PublishedMeasurementTypeTable,
        "filter": GenericPublishedListFilter,
    },
    "MeasurementStyle": {
        "display_name": camel_to_snake("MeasurementStyle"),
        "url": "measurement_styles",
        "model": MeasurementStyle,
        "table": PublishedMeasurementStyleTable,
        "filter": GenericPublishedListFilter,
    },
    "HomeBase": {
        "display_name": camel_to_snake("HomeBase"),
        "url": "homebases",
        "model": HomeBase,
        "table": PublishedHomeBaseTable,
        "filter": GenericPublishedListFilter,
    },
    "FocusArea": {
        "display_name": camel_to_snake("FocusArea"),
        "url": "focus_areas",
        "model": FocusArea,
        "table": PublishedFocusAreaTable,
        "filter": GenericPublishedListFilter,
    },
    "Season": {
        "display_name": camel_to_snake("Season"),
        "url": "seasons",
        "model": Season,
        "table": PublishedSeasonTable,
        "filter": GenericPublishedListFilter,
    },
    "Repository": {
        "display_name": camel_to_snake("Repository"),
        "url": "repositories",
        "model": Repository,
        "table": PublishedRepositoryTable,
        "filter": GenericPublishedListFilter,
    },
    "MeasurementRegion": {
        "display_name": camel_to_snake("MeasurementRegion"),
        "url": "measurement_regions",
        "model": MeasurementRegion,
        "table": PublishedMeasurementRegionTable,
        "filter": GenericPublishedListFilter,
    },
    "GeographicalRegion": {
        "display_name": camel_to_snake("GeographicalRegion"),
        "url": "geographical_regions",
        "model": GeographicalRegion,
        "table": PublishedGeographicalRegionTable,
        "filter": GenericPublishedListFilter,
    },
    "GeophysicalConcept": {
        "display_name": camel_to_snake("GeophysicalConcept"),
        "url": "geophysical_concepts",
        "model": GeophysicalConcept,
        "table": PublishedGeophysicalConceptTable,
        "filter": GenericPublishedListFilter,
    },
    "PartnerOrg": {
        "display_name": camel_to_snake("PartnerOrg"),
        "url": "partner_orgs",
        "model": PartnerOrg,
        "table": PublishedPartnerOrgTable,
        "filter": GenericPublishedListFilter,
    },
    "Alias": {
        "display_name": camel_to_snake("Alias"),
        "url": "aliases",
        "model": Alias,
        "table": PublishedAliasTable,
        "filter": GenericPublishedListFilter,
    },
    "GcmdProject": {
        "display_name": camel_to_snake("GcmdProject"),
        "url": "gcmd_projects",
        "model": GcmdProject,
        "table": PublishedGcmdProjectTable,
        "filter": GenericPublishedListFilter,
    },
    "GcmdInstrument": {
        "display_name": camel_to_snake("GcmdInstrument"),
        "url": "gcmd_instruments",
        "model": GcmdInstrument,
        "table": PublishedGcmdInstrumentTable,
        "filter": GenericPublishedListFilter,
    },
    "GcmdPlatform": {
        "display_name": camel_to_snake("GcmdPlatform"),
        "url": "gcmd_platforms",
        "model": GcmdPlatform,
        "table": PublishedGcmdPlatformTable,
        "filter": GenericPublishedListFilter,
    },
    "GcmdPhenomena": {
        "display_name": camel_to_snake("GcmdPhenomena"),
        "url": "gcmd_phenomena",
        "model": GcmdPhenomena,
        "table": PublishedGcmdPhenomenaTable,
        "filter": GenericPublishedListFilter,
    },
    "DOI": {
        "display_name": camel_to_snake("DOI"),
        "url": "dois",
        "model": DOI,
        "table": PublishedDOITable,
        "filter": GenericPublishedListFilter,
    },
    "Campaign": {
        "display_name": camel_to_snake("Campaign"),
        "url": "campaigns",
        "model": Campaign,
        "table": PublishedCampaignTable,
        "filter": GenericPublishedListFilter,
    },
    "Platform": {
        "display_name": camel_to_snake("Platform"),
        "url": "platforms",
        "model": Platform,
        "table": PublishedPlatformTable,
        "filter": GenericPublishedListFilter,
    },
    "Instrument": {
        "display_name": camel_to_snake("Instrument"),
        "url": "instruments",
        "model": Instrument,
        "table": PublishedInstrumentTable,
        "filter": GenericPublishedListFilter,
    },
    "Deployment": {
        "display_name": camel_to_snake("Deployment"),
        "url": "deployments",
        "model": Deployment,
        "table": PublishedDeploymentTable,
        "filter": GenericPublishedListFilter,
    },
    "IOP": {
        "display_name": camel_to_snake("IOP"),
        "url": "iops",
        "model": IOP,
        "table": PublishedIOPTable,
        "filter": GenericPublishedListFilter,
    },
    "SignificantEvent": {
        "display_name": camel_to_snake("SignificantEvent"),
        "url": "significant_events",
        "model": SignificantEvent,
        "table": PublishedSignificantEventTable,
        "filter": GenericPublishedListFilter,
    },
    "CollectionPeriod": {
        "display_name": camel_to_snake("CollectionPeriod"),
        "url": "collection_periods",
        "model": CollectionPeriod,
        "table": PublishedCollectionPeriodTable,
        "filter": GenericPublishedListFilter,
    },
    "Website": {
        "display_name": camel_to_snake("Website"),
        "url": "websites",
        "model": Website,
        "table": PublishedWebsiteTable,
        "filter": GenericPublishedListFilter,
    },
    "WebsiteType": {
        "display_name": camel_to_snake("WebsiteType"),
        "url": "website_types",
        "model": WebsiteType,
        "table": PublishedWebsiteTypeTable,
        "filter": GenericPublishedListFilter,
    },
    # "CampaignWebsite": {
    #     "display_name": camel_to_snake("CampaignWebsite"),
    #     "url": "campaign_websites",
    #     "model": CampaignWebsite,
    #     "table": PublishedCampaignWebsiteTable,
    #     "filter": GenericPublishedListFilter,
    # },
}