# Generated by Django 3.1.3 on 2020-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_deploy', 'Permissions to deploy website'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
