# Generated by Django 3.1.3 on 2022-11-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_app', '0016_auto_20220812_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
