# Generated by Django 4.1.5 on 2023-12-06 20:57

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0020_auto_20221109_0955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="update",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
