# Generated by Django 2.2.3 on 2019-07-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('gcmd_translation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('program_lead', models.CharField(max_length=256)),
                ('campaign_lead', models.CharField(max_length=256)),
                ('technical_contact', models.CharField(max_length=256)),
                ('publication_links', models.CharField(max_length=256)),
                ('online_resources', models.CharField(max_length=256)),
                ('repository_link', models.CharField(max_length=256)),
                ('partner_organizations', models.CharField(max_length=256)),
                ('partner_websites', models.CharField(max_length=256)),
                ('doi', models.CharField(max_length=256)),
                ('comments', models.CharField(max_length=2500)),
                ('public', models.BooleanField()),
                ('ongoing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('gcmd_translation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('gcmd_translation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('gcmd_translation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('gcmd_translation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('gcmd_translation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('gcmd_translation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('organization', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('online_information', models.CharField(max_length=256)),
                ('tail_numbers', models.CharField(max_length=256)),
                ('platform_model', models.CharField(max_length=256)),
                ('home_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='data_models.HomeBase')),
                ('platform_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='data_models.AircraftType')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('online_information', models.CharField(max_length=256)),
                ('instrument_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='data_models.InstrumentType')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments', models.ManyToManyField(related_name='flights', to='data_models.Instrument')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='data_models.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='data_models.Campaign')),
                ('platforms', models.ManyToManyField(related_name='campaigns', to='data_models.Platform')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='focus_areas',
            field=models.ManyToManyField(related_name='campaigns', to='data_models.FocusArea'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform_types',
            field=models.ManyToManyField(related_name='campaigns', to='data_models.PlatformType'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='repositories',
            field=models.ManyToManyField(related_name='campaigns', to='data_models.Repository'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='seasons',
            field=models.ManyToManyField(related_name='campaigns', to='data_models.Season'),
        ),
    ]
