# Generated by Django 2.0.8 on 2020-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='region',
            new_name='region_description',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='deployment_long_name',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='deployment_id',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='iopse',
            old_name='regional_description',
            new_name='region_description',
        ),
        migrations.AlterField(
            model_name='platform',
            name='gcmd_platform',
            field=models.ManyToManyField(related_name='platforms', to='data_models.GcmdPlatform'),
        ),
    ]
