# Generated by Django 2.2.3 on 2020-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeophysicalConcepts',
            new_name='GeophysicalConcept',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='gcmd_project',
            new_name='gcmd_projects',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='number_flights',
            new_name='number_collection_periods',
        ),
        migrations.RenameField(
            model_name='homebase',
            old_name='gcmd_translation',
            new_name='gcmd_uuid',
        ),
        migrations.RenameField(
            model_name='instrumenttype',
            old_name='gcmd_translation',
            new_name='gcmd_uuid',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='gcmd_platform',
            new_name='gcmd_platforms',
        ),
        migrations.RenameField(
            model_name='platformtype',
            old_name='gcmd_translation',
            new_name='gcmd_uuid',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='gcmd_translation',
            new_name='gcmd_uuid',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='nonaircraft_instruments',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='nonaircraft_platforms',
        ),
        migrations.AddField(
            model_name='focusarea',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
