# Generated by Django 2.2.3 on 2020-04-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='data_volume',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description_long',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description_short',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='doi',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='funding_program',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='funding_program_lead',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='gcmd_project',
            field=models.ManyToManyField(blank=True, default='', related_name='campaigns', to='data_models.GcmdProject'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='nasa_mission',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='nonaircraft_instruments',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='nonaircraft_platforms',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='number_data_products',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='other_resources',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='partner_orgs',
            field=models.ManyToManyField(blank=True, default='', related_name='campaigns', to='data_models.PartnerOrg'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='project_website',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='publication_links',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='repository_website',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='technical_contact',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='geographical_regions',
            field=models.ManyToManyField(blank=True, default='', related_name='deployments', to='data_models.GeographicalRegion'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='number_flights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='asp_long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='flight',
            name='campaign_deployment_base',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='flight',
            name='home_base',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instrument_information_source',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='flight',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='flight',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='flight',
            name='platform_owner',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='flight',
            name='platform_technical_contact',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='flight',
            name='tail_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='calibration_information',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='data_products_per_level',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='dates_of_operation',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='deployment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='facility',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='funding_source',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='gcmd_instruments',
            field=models.ManyToManyField(blank=True, default='', related_name='instruments', to='data_models.GcmdInstrument'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_doi',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_manufacturer',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='lead_investigator',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='online_information',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='repositories',
            field=models.ManyToManyField(blank=True, default='', related_name='instruments', to='data_models.Repository'),
        ),
        migrations.AlterField(
            model_name='iop',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='iop',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='iop',
            name='published_list',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='iop',
            name='reference_file',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='iop',
            name='reports',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='iop',
            name='short_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='platform',
            name='gcmd_platform',
            field=models.ManyToManyField(blank=True, default='', related_name='platforms', to='data_models.GcmdPlatform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='platform',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='platform',
            name='online_information',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='published_list',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='reference_file',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='reports',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='short_name',
            field=models.CharField(max_length=128),
        ),
    ]
