# Generated by Django 2.2.3 on 2020-04-21 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_auto_20200415_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasaMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(blank=True, default='', max_length=512)),
                ('notes_public', models.CharField(blank=True, default='', max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='project_lead',
            new_name='lead_investigator',
        ),
        migrations.RemoveField(
            model_name='gcmdinstrument',
            name='notes_public',
        ),
        migrations.RemoveField(
            model_name='gcmdplatform',
            name='gcmd_version',
        ),
        migrations.RemoveField(
            model_name='gcmdplatform',
            name='notes_public',
        ),
        migrations.RemoveField(
            model_name='gcmdplatform',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='gcmdproject',
            name='notes_public',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='measurement_keywords',
        ),
        migrations.RemoveField(
            model_name='partnerorg',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='partnerorg',
            name='notes_public',
        ),
        migrations.RemoveField(
            model_name='partnerorg',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platform_model',
        ),
        migrations.AddField(
            model_name='campaign',
            name='geophysical_concepts',
            field=models.ManyToManyField(related_name='campaigns', to='data_models.GeophysicalConcepts'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='nasa_led',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='gcmd_phenomenas',
            field=models.ManyToManyField(related_name='instruments', to='data_models.GcmdPhenomena'),
        ),
        migrations.AlterField(
            model_name='aircrafttype',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='aircrafttype',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='nasa_mission',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='gcmdinstrument',
            name='instrument_category',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdinstrument',
            name='instrument_class',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdinstrument',
            name='instrument_subtype',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdinstrument',
            name='instrument_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdinstrument',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='gcmdphenomena',
            name='term',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdphenomena',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdphenomena',
            name='variable_1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdphenomena',
            name='variable_2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdphenomena',
            name='variable_3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='gcmdplatform',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='gcmdproject',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='geophysicalconcepts',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='geophysicalconcepts',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='homebase',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='homebase',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='iop',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='iop',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='measurementregion',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='measurementregion',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='platform',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='platform',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='repository',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='repository',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='season',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='season',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='notes_internal',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='notes_public',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.DeleteModel(
            name='MeasurementKeyword',
        ),
        migrations.AddField(
            model_name='campaign',
            name='nasa_mission',
            field=models.ManyToManyField(blank=True, default='', related_name='campaigns', to='data_models.NasaMission'),
        ),
    ]
