# Generated by Django 2.0.8 on 2020-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_auto_20200305_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='short_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='short_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='flight',
            name='info_from_asp',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='short_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='iopse',
            name='short_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='platform',
            name='gcmd_platform',
            field=models.ManyToManyField(related_name='platforms', to='data_models.GcmdProject'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='short_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
