# Generated by Django 2.2.3 on 2020-08-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_auto_20200812_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='short_name',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
