# Generated by Django 2.2.3 on 2020-05-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_auto_20200507_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='homebase',
            name='gcmd_uuid',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='data_products_per_level',
        ),
        migrations.AddField(
            model_name='homebase',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='homebase',
            name='location',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='example',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='data_models.InstrumentType'),
        ),
        migrations.AddField(
            model_name='measurementregion',
            name='gcmd_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='gcmd_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='gcmd_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
