# Generated by Django 2.2.3 on 2020-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0004_doi_long_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doi",
            name="doi",
        ),
        migrations.AddField(
            model_name="doi",
            name="short_name",
            field=models.CharField(default="fake", max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
