# Generated by Django 2.2.3 on 2020-05-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0004_auto_20200507_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='nasa_mission',
            new_name='nasa_missions',
        ),
    ]
