# Generated by Django 2.0.8 on 2020-03-09 20:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0005_platform_gcmd_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='spatial_bounds',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
