# Generated by Django 2.2.3 on 2020-10-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0005_auto_20200925_0108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_models.Image",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_models.Image",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_models.Image",
            ),
        ),
    ]
