# Generated by Django 3.1.3 on 2020-11-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0006_auto_20201009_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doi',
            options={'verbose_name': 'DOI'},
        ),
    ]
