# Generated by Django 3.1.3 on 2020-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0007_auto_20201105_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='arbitrary_characteristics',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
