# Generated by Django 2.2.3 on 2020-10-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0010_auto_20201029_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='alias',
            new_name='short_name',
        ),
    ]
