# Generated by Django 3.1.3 on 2021-02-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0022_auto_20210216_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='websites',
            field=models.ManyToManyField(blank=True, default='', related_name='campaigns', through='data_models.CampaignWebsite', to='data_models.Website'),
        ),
    ]
