# Generated by Django 3.1.3 on 2021-02-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0023_auto_20210216_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='website_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='websites',
        ),
        migrations.DeleteModel(
            name='CampaignWebsite',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.DeleteModel(
            name='WebsiteType',
        ),
    ]
