# Generated by Django 3.1.3 on 2021-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0029_auto_20210331_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitetype",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
