# Generated by Django 3.1.3 on 2021-03-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0030_auto_20210331_1102"),
    ]

    operations = [
        migrations.AddField(
            model_name="focusarea",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="geographicalregion",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="geophysicalconcept",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="homebase",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="measurementregion",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="measurementstyle",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="measurementtype",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="partnerorg",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="platformtype",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="season",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="websitetype",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="campaignwebsite",
            name="priority",
            field=models.PositiveIntegerField(),
        ),
    ]
