# Generated by Django 3.1.3 on 2021-04-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0037_auto_20210428_1106"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="notes_internal",
            field=models.TextField(blank=True, default=""),
        ),
    ]
