# Generated by Django 3.1.3 on 2021-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0039_auto_20210429_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
