# Generated by Django 3.1.3 on 2021-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0041_auto_20210504_1359"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alias",
            name="model_name",
        ),
        migrations.AlterField(
            model_name="platform",
            name="stationary",
            field=models.BooleanField(verbose_name="Is the platform stationary?"),
        ),
    ]
