# Generated by Django 3.1.3 on 2021-12-13 23:19

from django.db import migrations, models
import django.db.models.deletion


def populate_website_campaign(apps, schema_editor):
    CampaignWebsite = apps.get_model("data_models", "CampaignWebsite")
    Website = apps.get_model("data_models", "Website")
    Change = apps.get_model("api_app", "Change")

    # Update published
    websites = []
    for campaign_website in CampaignWebsite.objects.prefetch_related("website").all():
        campaign_website.website.campaign_id = campaign_website.campaign_id
        campaign_website.website.order_priority = campaign_website.order_priority
        websites.append(campaign_website.website)
    Website.objects.bulk_update(websites, ["campaign_id", "order_priority"])

    # Update drafts
    for draft in Change.objects.filter(content_type__model="campaignwebsite"):
        Change.objects.filter(content_type__model="website").filter(
            model_instance_uuid=draft.update["website"]
        ).update(update__campaign_id=draft.update["campaign"])


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0042_auto_20210524_1546"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_models.campaign",
            ),
        ),
        migrations.AddField(
            model_name='website',
            name='order_priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_website_campaign, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="websites",
        ),
        migrations.DeleteModel(
            name="CampaignWebsite",
        ),
        migrations.AlterField(
            model_name="website",
            name="campaign",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_models.campaign",
            ),
        ),
    ]
