# Generated by Django 3.1.3 on 2022-02-03 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0043_auto_20211213_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='data_models.campaign'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
