# Generated by Django 3.1.3 on 2022-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0044_auto_20220203_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='doi',
            name='cmr_data_format',
            field=models.TextField(blank=True, default=''),
        ),
    ]
