# Generated by Django 3.1.3 on 2022-05-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('data_models', '0045_auto_20220516_1535')]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='collectionperiod',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='collectionperiod',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='geophysicalconcept',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='geophysicalconcept',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='homebase',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='homebase',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='measurementregion',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='measurementregion',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='measurementstyle',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='measurementstyle',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='partnerorg',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='partnerorg',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='platform',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='platform',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='repository',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='repository',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='season',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='season',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='website',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='websitetype',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='websitetype',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
    ]

