# Generated by Django 3.1.3 on 2022-05-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('data_models', '0046_auto_20220516_1551')]

    operations = [
        migrations.RenameModel(old_name='GcmdPhenomena', new_name='GcmdPhenomenon'),
        migrations.AlterModelOptions(
            name='gcmdphenomenon', options={'verbose_name_plural': 'Phenomena'}
        ),
        migrations.RenameField(
            model_name='instrument', old_name='gcmd_phenomenas', new_name='gcmd_phenomena'
        ),
    ]
