# Generated by Django 3.1.3 on 2022-07-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0048_auto_20220708_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcmdplatform',
            name='category',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
