# Generated by Django 3.1.3 on 2022-08-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0050_auto_20220812_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcmdplatform',
            old_name='crazynewcategory',
            new_name='category',
        ),
    ]
