# Generated by Django 3.1.3 on 2023-02-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0051_auto_20220812_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='spatial_bounds',
        ),
    ]
