# Generated by Django 4.1.5 on 2023-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0052_remove_campaign_spatial_bounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doi',
            name='cmr_data_formats',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doi',
            name='cmr_dates',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doi',
            name='cmr_plats_and_insts',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doi',
            name='cmr_projects',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doi',
            name='cmr_science_keywords',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
