import json
from cmr.cmr import query_and_process_cmr


def generate_cmr_response():
    """Many of our processes rely on first getting information from the CMR API.
    This function is only run once and it saves a sample CMR file to the repository.
    All test functions that rely on CMR will use this file, and there is a separate test
    that evaluates whether CMR still gives the same response.

    To run this function and generate the file, use a manage.py shell
    """

    return query_and_process_cmr('campaign', ['ACES'])


def save_cmr_response(cmr_metadata):
    """saves the cmr response generated by generate_cmr_response"""

    json.dump(cmr_metadata, open('cmr/tests/cmr_response_aces.json', 'w'))


if __name__ == '__main__':
    cmr_response = generate_cmr_response()
    save_cmr_response(cmr_response)
