import json

from cmr.cmr import query_and_process_cmr


def generate_cmr_response(campaign_short_name):
    """Many of our processes rely on first getting information from the CMR API.
    This function is only run once and it saves a sample CMR file to the repository.
    All test functions that rely on CMR will use this file, and there is a separate test
    that evaluates whether CMR still gives the same response.

    To run this function and generate the file, use a manage.py shell
    """

    return query_and_process_cmr('campaign', [campaign_short_name])


def save_cmr_response(cmr_metadata, file_name):
    """saves the cmr response generated by generate_cmr_response"""

    json.dump(cmr_metadata, open(f'cmr/tests/{file_name}', 'w'))


def generate_ascends_data():
    cmr_response = generate_cmr_response('ASCENDS Airborne')
    save_cmr_response(cmr_response, 'cmr_response-ASCENDS.json')
