# Generated by Django 2.2.3 on 2020-04-08 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='model_instance_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
