# Generated by Django 2.2.3 on 2020-04-10 00:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0003_auto_20200408_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="change",
            name="previous",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="change",
            name="status",
            field=models.IntegerField(
                choices=[(2, "Pending"), (3, "Approved"), (1, "IN_PROGRESS")], default=1
            ),
        ),
    ]
