# Generated by Django 3.1.3 on 2020-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_auto_20201105_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='action',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Patch', 'Patch')], default='Create', max_length=10),
        ),
        migrations.AlterField(
            model_name='change',
            name='previous',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='change',
            name='status',
            field=models.IntegerField(choices=[(2, 'Pending'), (3, 'Approved'), (1, 'In Progress')], default=1),
        ),
        migrations.AlterField(
            model_name='change',
            name='update',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
