# Generated by Django 3.1.3 on 2021-01-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api_app', '0007_auto_20201211_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'verbose_name': 'Draft'},
        ),
        migrations.AlterField(
            model_name='change',
            name='content_type',
            field=models.ForeignKey(help_text='Model for which the draft pertains.', limit_choices_to={'app_label': 'data_models', 'model__in': ['campaign', 'instrument', 'platform', 'iop', 'deployment', 'partnerorg']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
