# Generated by Django 3.1.3 on 2021-03-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0011_auto_20210301_1524"),
        ("api_app", "0011_auto_20210301_1315"),
    ]

    operations = []
