# Generated by Django 3.1.3 on 2021-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_auto_20210421_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='field_status_tracking',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
