# Generated by Django 3.1.3 on 2022-04-28 04:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api_app', '0015_change_field_status_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedLog',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('recommended_uuid', models.UUIDField()),
                (
                    'result',
                    models.BooleanField(blank=True, verbose_name='Was the CASEI object connected?'),
                ),
                (
                    'change_uuid',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='api_app.change'
                    ),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
        ),
    ]
