# Generated by Django 3.1.3 on 2022-07-12 13:11

from api_app.models import Change
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid


def transition_patch_to_update(apps, schema_editor):
    Change.objects.filter(action='Patch').update(action=Change.Actions.UPDATE)


class Migration(migrations.Migration):

    replaces = [
        ('api_app', '0016_remove_patch'),
        ('api_app', '0016_resolvedlog'),
        ('api_app', '0017_auto_20220427_2338'),
        ('api_app', '0018_auto_20220427_2345'),
        ('api_app', '0019_auto_20220427_2359'),
        ('api_app', '0020_auto_20220428_0005'),
        ('api_app', '0021_auto_20220428_0920'),
        ('api_app', '0022_auto_20220428_0921'),
        ('api_app', '0023_auto_20220428_0922'),
        ('api_app', '0024_recommendation_resolvedlist'),
        ('api_app', '0025_auto_20220428_1111'),
        ('api_app', '0026_auto_20220428_2121'),
        ('api_app', '0027_auto_20220505_1334'),
        ('api_app', '0028_recommendation_resolvedlist'),
        ('api_app', '0029_auto_20220615_1315'),
        ('api_app', '0030_merge_20220627_2108'),
        ('api_app', '0031_auto_20220708_1516'),
    ]

    dependencies = [
        ('api_app', '0015_change_field_status_tracking'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(
            code=transition_patch_to_update,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='change',
            name='action',
            field=models.CharField(
                choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')],
                default='Update',
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('object_uuid', models.UUIDField()),
                (
                    'result',
                    models.BooleanField(null=True, verbose_name='Was the CASEI object connected?'),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'change',
                    models.ForeignKey(
                        default=uuid.uuid4(),
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api_app.change',
                    ),
                ),
                (
                    'submitted',
                    models.BooleanField(
                        default=False, verbose_name='Has the user published their result?'
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(
                fields=('change', 'object_uuid'), name='unique_recommendation'
            ),
        ),
    ]
