# Generated by Django 3.1.3 on 2022-07-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='change',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='api_app.change'
            ),
        ),
    ]
