# Generated by Django 3.1.3 on 2022-04-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api_app', '0017_auto_20220427_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Recommendations',
        ),
        migrations.RemoveField(
            model_name='resolvedlog',
            name='result',
        ),
        migrations.AddField(
            model_name='resolvedlog',
            name='recomendation',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api_app.recommendations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolvedlog',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='Form has been submitted by user.'),
        ),
    ]
