# Generated by Django 3.1.3 on 2022-04-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0018_auto_20220427_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolvedlog',
            name='change_uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.change'),
        ),
    ]
