# Generated by Django 3.1.3 on 2022-11-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0018_auto_20221108_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
