# Generated by Django 3.1.3 on 2022-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_app', '0019_auto_20221108_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
