# Generated by Django 3.1.3 on 2022-04-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_auto_20220427_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolvedlog',
            name='change_uuid',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.change'
            ),
        ),
        migrations.AlterField(
            model_name='resolvedlog',
            name='recomendation',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.recommendations'
            ),
        ),
    ]
