# Generated by Django 3.1.3 on 2022-04-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0021_auto_20220428_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResolvedLog',
            new_name='ResolvedList',
        ),
    ]
