# Generated by Django 3.1.3 on 2022-04-28 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api_app', '0023_auto_20220428_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted', models.BooleanField(default=False, verbose_name='Form has been submitted by user.')),
                ('change_uuid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.change')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_uuid', models.UUIDField()),
                ('result', models.BooleanField(blank=True, verbose_name='Was the CASEI object connected?')),
                ('content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('resolved_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.resolvedlist')),
            ],
        ),
    ]
