# Generated by Django 3.1.3 on 2022-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0024_recommendation_resolvedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='result',
            field=models.BooleanField(null=True, verbose_name='Was the CASEI object connected?'),
        ),
    ]
