# Generated by Django 3.1.3 on 2022-04-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0025_auto_20220428_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolvedlist',
            old_name='change_uuid',
            new_name='change',
        ),
    ]
