# Generated by Django 3.1.3 on 2022-06-15 18:15

from django.db import migrations, models
from uuid import uuid4
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0028_recommendation_resolvedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='resolved_log',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='change',
            field=models.ForeignKey(
                default=uuid4(), on_delete=django.db.models.deletion.CASCADE, to='api_app.change'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='submitted',
            field=models.BooleanField(
                default=False, verbose_name='Has the user published their result?'
            ),
        ),
        migrations.DeleteModel(
            name='ResolvedList',
        ),
    ]
