# Generated by Django 3.1.3 on 2022-06-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0029_auto_20220615_1315'),
        ('api_app', '0016_remove_patch'),
    ]

    operations = []
