# Generated by Django 3.1.3 on 2022-07-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0030_merge_20220627_2108'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('change', 'object_uuid'), name='unique_recommendation'),
        ),
    ]
