# Generated by Django 2.2.3 on 2021-01-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0016_auto_20201218_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionperiod",
            name="home_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_periods",
                to="data_models.HomeBase",
            ),
        ),
    ]
