# Generated by Django 3.1.3 on 2022-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('data_models', '0045_auto_20220509_1448')]

    operations = [
        migrations.RenameModel(old_name='GcmdPhenomena', new_name='GcmdPhenomenon'),
        migrations.AlterModelOptions(
            name='gcmdphenomenon', options={'verbose_name_plural': 'Phenomena'}
        ),
        migrations.RenameField(
            model_name='instrument', old_name='gcmd_phenomenas', new_name='gcmd_phenomena'
        ),
        migrations.AlterField(
            model_name='instrument',
            name='gcmd_phenomena',
            field=models.ManyToManyField(
                help_text='Select relevant measurements/variables items from GCMD Science Keywords for Earth Science',
                related_name='instruments',
                to='data_models.GcmdPhenomenon',
                verbose_name='Measurements/Variables from GCMD Science Keywords',
            ),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='collectionperiod',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='collectionperiod',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='geophysicalconcept',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='geophysicalconcept',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='homebase',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='homebase',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='measurementregion',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='measurementregion',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='measurementstyle',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='measurementstyle',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='partnerorg',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='partnerorg',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='platform',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='platform',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='repository',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='repository',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='season',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='season',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
        migrations.AlterField(
            model_name='website',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='websitetype',
            name='notes_internal',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Free text notes for ADMG staff, this is NOT visible to the public.',
            ),
        ),
        migrations.AlterField(
            model_name='websitetype',
            name='notes_public',
            field=models.TextField(
                blank=True, default='', help_text='Free text notes, this IS visible to the public.'
            ),
        ),
    ]
