# Generated by Django 4.1.5 on 2023-06-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data_models', '0055_auto_20230613_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doi',
            name='cmr_data_formats',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doi',
            name='cmr_dates',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doi',
            name='cmr_plats_and_insts',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doi',
            name='cmr_projects',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doi',
            name='cmr_science_keywords',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
