name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      role-to-assume:
        type: string
        required: true
      role-session-name:
        type: string
        required: false
        default: github-actions-deployment
      environment:
        type: string
        required: true
      aws-region:
        type: string
        required: false
        default: us-west-2
      vpc-id:
        description: ID of AWS VPC.
        type: string
        required: true
      domain-name:
        description: Name of the domain from which the application is served.
        type: string
        required: true
      alb-listener-arn:
        description: ARN of Application Load Balancer listener.
        type: string
        required: true
      django-debug:
        description: Enable DEBUG mode in Django.
        type: boolean
        required: false
        default: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      VPC_ID: ${{ inputs.vpc-id }}
      DOMAIN_NAME: ${{ inputs.domain-name }}
      ALB_LISTENER_ARN: ${{ inputs.alb-listener-arn }}
      # Django Settings
      DJANGO_DEBUG: ${{ inputs.django-debug }}
      DJANGO_ADMIN_URL: ${{ secrets.DJANGO_ADMIN_URL }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_SECURE_SSL_REDIRECT: ${{ secrets.DJANGO_SECURE_SSL_REDIRECT }}
      DJANGO_SETTINGS_MODULE: ${{ vars.DJANGO_SETTINGS_MODULE }}
      CASEI_GH_TOKEN: ${{ secrets.CASEI_GH_TOKEN }}
      # DB Credentials for RDS instance
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      # Other
      GCMD_SYNC_RECIPIENTS: ${{ secrets.GCMD_SYNC_RECIPIENTS }}
      GCMD_SYNC_SOURCE_EMAIL: ${{ secrets.GCMD_SYNC_SOURCE_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ github.actor }}
          aws-region: ${{ inputs.aws-region }}

      - name: Install dependencies
        run: |
          pip install -r deploy/requirements.txt

      - name: CDK Deploy
        run: |
          npx cdk deploy \
            "*-application" \
            --exclusively \
            --require-approval never
