name: Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_ENGINE: django.contrib.gis.db.backends.postgis
      DB_NAME: admg
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: config.settings.local
      DJANGO_SECRET_KEY: "secret key here"
      DJANGO_ADMIN_URL: admg/
      GH_TOKEN: faketokenhere
      GCMD_SYNC_SOURCE_EMAIL: gcmdadmg@localhost
      GCMD_SYNC_RECIPIENTS: gcmd@localhost
      CELERY_BROKER_URL: amqp://guest:guest@localhost:5672/

    services:
      postgres:
        image: postgis/postgis:13-3.2
        env:
          POSTGRES_DB: admg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:latest
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install libgdal-dev

      - uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements/base.txt') }}-${{ hashFiles('requirements/local.txt') }}

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          pip install \
            --upgrade \
            --upgrade-strategy eager \
            -r requirements/base.txt \
            -r requirements/local.txt

      - name: Install Playwright
        run: |
          playwright install --with-deps

      - name: Save Test Videos
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: videos/

      - name: Check for missing migrations
        run: |
          python manage.py makemigrations --check --dry-run

      - name: Run Tests
        run: |
          coverage run -m pytest
          coverage report -m --skip-covered
          coverage json -o coverage.json

      - name: Save Code Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code_coverage
          path: coverage.json

  compare-coverage:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref_name != 'dev'}}

    steps:
      - uses: actions/checkout@v2

      - name: Get Commit Coverage
        uses: actions/download-artifact@v3
        with:
          name: code_coverage
          path: new_cov

      - name: Get Dev Coverage
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: dev
          name: code_coverage
          path: dev_cov
          if_no_artifact_found: fail

      - name: Calculate Coverage
        id: calculate_coverage
        run: |
          new_cov=$(cat ./new_cov/coverage.json)
          echo "new_cov=${new_cov//'%'/'%25'}" >> $GITHUB_OUTPUT
          dev_cov=$(cat ./dev_cov/coverage.json)
          echo "dev_cov=${dev_cov//'%'/'%25'}" >> $GITHUB_OUTPUT

      - name: Compare Coverage
        id: compare_coverage
        run: |
          dev_total="${{fromJson(steps.calculate_coverage.outputs.dev_cov).totals.percent_covered}}"
          new_total="${{fromJson(steps.calculate_coverage.outputs.new_cov).totals.percent_covered}}"
          (( $(echo "$new_total < $dev_total" | bc -l) )) && result=failure || result=success
          echo "result=${result}" >> $GITHUB_OUTPUT
          echo "Coverage comparison: $result"

      - name: Report result
        if: ${{steps.compare_coverage.outputs.result=='failure'}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Test coverage on source branch is lower than on dev branch')
